server:
  port: 8080
spring:
  kafka:
    producer:
      retries: 1
      bootstrap-servers: 192.168.78.128:9092
    consumer:
      bootstrap-servers: 192.168.78.128:9092
  redis:
    database: 0
    host: 192.168.78.128
    port: 6379
    password:

logging:
  level:
    root: INFO